# Site
name: "Codexponent"
title: "Codexponent"
description: "Technical blogs based on Ruby on Rails, React, AWS and Docker."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'G-4B0GEHN8ET'
url: https://codexponent.com
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Kalpit:
    name: Kalpit
    display_name: Kalpit
    avatar: 'assets/images/kalpit.jpeg'
    gravatar: 'e56154546cf4be74e393c62d1ae9f9d4'
    email: choudharikalpit120@gmail.com
    description: "Full stack developer working on Ruby on Rails and React"
  Mayuresh:
    name: Mayuresh
    display_name: Mayuresh    
    avatar: 'assets/images/mayuresh.jpeg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: pawarmayuresh29@gmail.com
    description: "Full stack developer working on Ruby on Rails and React"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
